CREATE TABLE IF NOT EXISTS `cittadini_or_acc` (
`id_cittadino_or_acc` INT NOT NULL AUTO_INCREMENT,	
`data_assegnazione` DATE NOT NULL,
`data_scadenza` DATE NOT NULL,
`id_beneficio` INT NOT NULL,
`misura` VARCHAR(40) NOT NULL COMMENT '"1 - Reinserimento Lavorativo", "2 - Upskilling", "3 - Reskilling", "Accompagnamento", "4 - Lavoro e inclusione", "Acc. all\'avvio d\'impresa"',
`id_lavoro` INT NULL COMMENT 'lavoro obiettivo',
`preferenza_ente_acc_lav` VARCHAR(30) NULL COMMENT '"Acc Meschini"/"Acc altro ente"',
`id_corso` INT NULL COMMENT 'corso scelto in orientamento',
`ente` VARCHAR(30) NULL COMMENT 'Meschini, altro o vuoto -> id_ente ???',
`sede` VARCHAR(30) NULL COMMENT 'sede ente',
`id_cittadino` INT NOT NULL,
`acc_da_or_p1` CHAR(1) NOT NULL COMMENT '0 o 1',
`data_di_lavorazione` VARCHAR(50) NULL,
`cpi` VARCHAR(30) NOT NULL,
`id_stato_intervento` INT NULL,
`note` VARCHAR(255) NULL,
`stato_corso` VARCHAR(30) NOT NULL COMMENT '"Andrà al CPI", "Prova con SPID da solo", "Iscritto", "Avvisato", "Non partecipa"',
`id_omls` INT NULL,
`stato` VARCHAR(100) NULL COMMENT 'state: "DA RENDICONTARE", "DA RENDICONTARE IV TRIMESTRE", "IN CORSO", "PROSSIMO TRIMESTRE", "RENDICONTATO", "RINUNCIA"',
`rendicontazione` VARCHAR(100) NULL ,
`profilo_prof` VARCHAR(100) NULL COMMENT 'profilo professionale',
`ob_lav_raggiunto` VARCHAR(50) NULL COMMENT '"T.I", "T.D >= 6 MESI", "T.D < 6 MESI", "APPR"',
`data1_incontro` DATE NULL COMMENT 'data 1° incontro',
`orario1_inizio` TIME COMMENT 'da  ore',
`durata1` DECIMAL(5,2) COMMENT 'n. ore',
`data2_incontro` DATE NULL COMMENT 'data 2° incontro',
`orario2_inizio` TIME COMMENT 'da ore',
`durata2` DECIMAL(5,2) COMMENT 'n. ore',
`annotazioni` VARCHAR(255) NULL COMMENT 'annotazioni per sostituire la formattazione celle e, a quanto pare, `note` non basta!',
`ore_totali` mediumint(9) NOT NULL COMMENT 'meglio qui che in `interventi_gol`',
`ore_svolte` mediumint(9) NOT NULL COMMENT 'meglio qui che in `interventi_gol`',
PRIMARY KEY (`id_cittadino_or_acc`)
) DEFAULT CHARSET=utf8 COMMENT 'file: "LINK OR ACC T.S..xlsx"';