CREATE TABLE IF NOT EXISTS `gestioni_appuntamenti` (
`id_ga` INT NOT NULL AUTO_INCREMENT,
`id_omls` INT NOT NULL,
`id_cittadino` INT NOT NULL,
`attivita` VARCHAR(40) NOT NULL COMMENT '"AL", "ACC", "orientamento", "OR", "Accompagnamento",
"3 - Reskilling", "1 - Reinserimento Lavorativo", "2 - Upskilling", "Acc Lav",
"OS", "Orientamento ", "ost", "ORI", "Accompagnamento ", "ACC "',
`link` VARCHAR(255) NULL COMMENT 'link di meet oppure IN PRESENZA',
`data` DATE NULL,
`orario_inizio` TIME NULL,
`durata` DECIMAL(5,2) NULL,
`tipologia_orientamento` CHAR(5) NOT NULL COMMENT '"I" = "individuale", "G" = "di gruppo"',
`modifiche` VARCHAR(255) NULL,
`note_comunicazioni` VARCHAR(255) NULL COMMENT 'note/comunicazioni',
`annotazioni` VARCHAR(255) NULL COMMENT 'annotazioni per sostituire la formattazione celle e, a quanto pare, `modifiche` e `note_comunicazioni` non bastano!',
`m1` TINYINT(1) NULL COMMENT 'mail - M1 (mail finale inviata a utente? V/F)',
`sg1` TINYINT(1) NULL COMMENT 'SKILL GAP 1^ domanda - SG1 (nome e cognome non scambiati? V/F)',
`sg2` TINYINT(1) NULL COMMENT 'SKILL GAP 2^ domanda - SG2 (firma autografata? V/F)',
`doc_id1` TINYINT(1) NULL COMMENT 'DOC ID - doc id 1 (unico file in pdf caricato? V/F)',
`pr1` TINYINT(1) NULL COMMENT 'Privacy - pr1 (data e firma autografata inserita? V/F)',
`cv1` TINYINT(1) NULL COMMENT 'CV - CV1 (data e firma autografata inserita? V/F)',
`sp1` TINYINT(1) NULL COMMENT 'Scheda profilo - SP 1 (caricata in formato word? V/F)',
`bp1` TINYINT(1) NULL COMMENT 'Bilancio Competenze - BP1 (caricato in formato pdf? V/F)',
`mc1` TINYINT(1) NULL COMMENT 'Modulo Conclusivo - mc acc1 (firmato solo dall\'utente? V/F)',
PRIMARY KEY (`id_ga`)
) DEFAULT CHARSET=utf8 COMMENT 'fogli: Mese-Anno | link_or_acc, file: "APPUNTAMENTI OR_ACC (1).xlsx" | "LINK OR ACC T.S..xlsx"';